name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: react  # This uses the runner labeled 'frontend'

    steps:
      - name: Set up SSH key for GitHub Actions
        run: |
          if [ ! -d "$HOME/.ssh" ]; then mkdir -p ~/.ssh; fi
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa1
          sudo chown -R $USER:$USER ~/.ssh
          sudo chmod 600 ~/.ssh/id_rsa1
          sudo chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          node -v

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Pull and Deploy Frontend
        working-directory: /var/www/reactapp/client
        run: |
          echo "Pulling latest code for frontend"
          git pull origin master
          
          # Install dependencies
          npm install --force

          # Create build in a temporary directory
          echo "Building the frontend application"
          npm run build

          echo "Using rsync for atomic deployment"
          TEMP_BUILD_DIR="/var/www/html/temp_build"
          
          # Sync build files to the temporary directory
          rsync -av --delete ./build/ $TEMP_BUILD_DIR/

          # Ensure the old build is not deleted until the new build is completely ready
          echo "Switching to the new build"
          mv $TEMP_BUILD_DIR /var/www/reactapp/client/build

          # Set correct permissions for the new build
          sudo chown -R www-data:www-data /var/www/reactapp/client/build
          sudo chmod -R 755 /var/www/reactapp/client/build

          echo "Deployment complete! The new build is now live."
