name: Frontend Deployment

on:
  push: 
    branches:
      - master

jobs:
  frontend:
    runs-on: [self-hosted, react]

    steps:
      - name: Set up SSH key for GitHub Actions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa1
          chmod 600 ~/.ssh/id_rsa1
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Use default GitHub Actions directory
        run: |
          echo "Default directory: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      - name: Build frontend
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run build

      - name: Rsync build to production directory
        run: |
          rsync -av --delete $GITHUB_WORKSPACE/build/ /var/www/reactapp/client/build/

      - name: Clean up temporary build files
        run: |
          rm -rf $GITHUB_WORKSPACE/build
