name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: [self-hosted, react]

    steps:
      - name: Set up SSH key for GitHub Actions
        run: |
          if [ ! -d "$HOME/.ssh" ]; then mkdir -p ~/.ssh; fi
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa1
          sudo chown -R $USER:$USER ~/.ssh
          sudo chmod 600 ~/.ssh/id_rsa1
          sudo chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Backup current node_modules and build directory
        run: |
          # Backup the current node_modules directory to temp
          mv /var/www/reactapp/client/node_modules /var/www/reactapp/client/node_modules_backup || true
          # Backup the current build directory to temp
          mv /var/www/reactapp/client/build /var/www/reactapp/client/build_backup || true

      - name: Pull latest code for frontend
        working-directory: /var/www/reactapp/client
        run: |
          echo "Pulling latest code for frontend"
          git pull origin master

      - name: Build frontend in a temporary directory
        working-directory: /var/www/reactapp/client
        run: |
          TEMP_BUILD_DIR="/var/www/reactapp/client/temp_build"
          echo "Building frontend in a temporary directory"
          # Create a temporary directory for building
          mkdir -p $TEMP_BUILD_DIR
          mv /var/www/reactapp/client/node_modules_backup /var/www/reactapp/client/node_modules
          npm install
          npm run build

      - name: Move build to production directory
        run: |
          # Only move the build if successful
          rsync -av --delete /var/www/reactapp/client/temp_build/build/ /var/www/reactapp/client/build/
          # Clean up
          rm -rf /var/www/reactapp/client/temp_build

      - name: Restore original node_modules if needed
        run: |
          # If any issue occurs, restore the original node_modules
          if [ -d "/var/www/reactapp/client/node_modules_backup" ]; then
            mv /var/www/reactapp/client/node_modules_backup /var/www/reactapp/client/node_modules
          fi
